name: raag
description: Music Player made using Flutter

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: ">=2.7.0 <3.0.0"

dependencies:
  animated_icon_button: ^0.3.0
  animator: ^2.0.2
  audio_manager: ^0.5.5+3
  audioplayer: 0.8.1
  audioplayer_web: 0.7.1
  clipboard: ^0.1.2+8
  connectivity: ^2.0.2
  downloads_path_provider_28: ^0.1.0
  flutter_audio_query: ^0.3.5+6
  fluttertoast: ^7.1.1
  marquee: ^1.6.1
  provider: ^4.3.2+2
  rflutter_alert: ^1.1.0
  shared_preferences: ^0.5.10
  webview_flutter: ^1.0.7
  youtube_explode_dart: ^1.3.0

  flutter:
    sdk: flutter


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  uses-material-design: true
  assets:
    - assets/images/
  fonts:
    - family: Passion One
      fonts:
        - asset: assets/fonts/PassionOne-Regular.ttf
        - asset: assets/fonts/PassionOne-Bold.ttf
          weight: 700
    - family: Alata
      fonts:
        - asset: assets/fonts/Alata-Regular.ttf
    - family: YouTubeIcon
      fonts:
        - asset: assets/fonts/YouTubeIcon.ttf